package com.castprogramms.newinvestgame.tools

import com.castprogramms.newinvestgame.R

enum class Companies(var cent: Double, var country: Countries, var industry: Industries, var nameCompany: String, var img: Int, var opisanie: String) {
    Apple(310.13,
        Countries.USA,
        Industries.Software,
        "Apple",
        R.mipmap.apple,
        "Американская корпорация, производитель персональных и планшетных компьютеров, аудиоплееров, телефонов, программного обеспечения. "),
    Intel(59.62,
        Countries.USA,
        Industries.Software,
        "Intel",
        R.mipmap.intel,
        "Транснациональная корпорация, производитель электронных устройств и компьютерных компонентов, включая полноцикловое производство микропроцессоров и наборов системной логики (чипсетов)."),
    Twitter(29.83,
        Countries.USA,
        Industries.Software,
        "Twitter",
        R.mipmap.twitter,
        "Социальная сеть для публичного обмена сообщениями при помощи веб-интерфейса, SMS, средств мгновенного обмена сообщениями или сторонних программ-клиентов для пользователей интернета любого возраста."),
    Mailru(16.42,
        Countries.GreatBritain,
        Industries.Software,
        "Mail.ru",
        R.mipmap.mailru,
        "Русскоязычный интернет-портал, принадлежащий технологической компании Mail.ru Group."),
    Facebook(212.53,
        Countries.USA,
        Industries.Software,
        "Facebook",
        R.mipmap.facebook,
        "Крупнейшая социальная сеть в мире и одноимённая компания (Facebook Inc.), владеющая ею."),
    Yandex(40.74,
        Countries.Russia,
        Industries.Software,
        "Yandex",
        R.mipmap.yandex,
        "Российская транснациональная компания в отрасли информационных технологий, зарегистрированная в Нидерландах и владеющая одноимённой системой поиска в Сети, интернет-порталами и службами в нескольких странах. Одна из крупнейших российских IT- и интернет-компаний."),
    Amazon(2379.4,
        Countries.USA,
        Industries.Software,
        "Amazon",
        R.mipmap.amazon,
        "Американская компания, крупнейшая в мире на рынках платформ электронной коммерции и публично-облачных вычислений по выручке и рыночной капитализации."),
    MasterCard(282.7,
        Countries.USA,
        Industries.BankingIndustry,
        "MasterCard",
        R.mipmap.master_card,
        "Аеждународная платёжная система, транснациональная финансовая корпорация, объединяющая 22 тысячи финансовых учреждений в 210 странах мира."),
    IBM(123.2,
        Countries.USA,
        Industries.Software,
        "IBM",
        R.mipmap.ibm,
        "Американская компания со штаб-квартирой в Армонке (штат Нью-Йорк), один из крупнейших в мире производителей и поставщиков аппаратного и программного обеспечения, а также IТ-сервисов и консалтинговых услуг."),
    GazProm(203.33,
        Countries.Russia,
        Industries.OilIndustry,
        "GazProm",
        R.mipmap.gazprom,
        "Pоссийская транснациональная энергетическая компания, более 50 % акций которой принадлежит государству."),
    Lukoil(4.83,
        Countries.Russia,
        Industries.OilIndustry,
        "Lukoil",
        R.mipmap.lukoil,
        "Pоссийская нефтяная компания. Вторая после «Газпрома» по объёмам выручки компания в России (по итогам 2014 года, по данным журнала «Эксперт»)."),
    CocaCola(46.14,
        Countries.Germany,
        Industries.FoodIndustry,
        "Coca-Cola",
        R.mipmap.coca,
        "Безалкогольный газированный напиток, производимый компанией «The Coca-Cola Company». «Кока-Кола» была признана одним из самых дорогих брендов в мире в 2005—2015 годах в рейтинге международного исследовательского агентства Interbrand."),
    McDonalds(181.67,
        Countries.USA,
        Industries.FoodIndustry,
        "McDonald's",
        R.mipmap.mcdonalds,
        "Американская корпорация, работающая в сфере общественного питания, до 2010 года крупнейшая в мире сеть ресторанов быстрого питания, работающая по системе франчайзинга. "),
    Microsoft(184.67,
        Countries.USA,
        Industries.Software,
        "Microsoft",
        R.mipmap.micro,
        "Одна из крупнейших транснациональных компаний по производству проприетарного программного обеспечения для различного рода вычислительной техники — персональных компьютеров, игровых приставок, КПК, мобильных телефонов и прочего, разработчик наиболее широко распространённой на данный момент в мире программной платформы — семейства операционных систем Windows."),
    Huawei(3.01,
        Countries.China,
        Industries.Software,
        "Huawei",
        R.mipmap.huawei,
        "Одна из крупнейших мировых компаний в сфере телекоммуникаций. Основана в 1987 году, бывшим инженером Народно-освободительной армии Китая Жэнь Чжэнфэем.")
}